
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Capa_Entidad
{

using System;
    using System.Collections.Generic;
    
public partial class Loogin
{

    public int Id { get; set; }

    public string Usuario { get; set; }

    public string Contrasena { get; set; }

    public string Nombre { get; set; }

}

}
